#_config for theme ego
cusdis:
  enable: false
  host: 
  appId: 

disqusjs:
  enable: true
  shortname: JiPai Store
  siteName: JiPai Store
  api: https://disqus.skk.moe/disqus/
  apikey: XmzmGKEBpV11VlOd0K8QJnDOIsJRsW6y9vf6DO6Nw2MkWXkSGvqYSReey9btEU7U
  admin: jipai
  adminLabel: MOD